# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84ef76ac4911c2ad8d1aa02ad3c80bd61b8b0012ebc90c647ee44b5d271f2ca6db79c58ad845d2061f41b816cb2455a8f9072c198565a4b1d0e45158c3e44f9c

test:
  secret_key_base: d10e1f3c0eea8a2268523ad3e57f900aa676f5381cad7aa2a804af41b2846fe6489ddf7fc6bd6c67f838c6894771d3a1e9e7bdef317d188288ab16096e2495f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
